### ISSUE TITLE
DB Table 관련해서

### ISSUE THREAD

**Issue by Charlie-Junhyung** [jungmin88/ProjectMaliys#1]
테이블은 하나밖에 없는게 맞는거같은데 
속성을 어떻게 뽑아내는게 좋을까요 

- 날짜
- 위치 기록
- 이미지 경로 (갯수?)
- 날씨 
- 기분
- 본문

일단 이정도로 뽑았는데,
약간 아리송한 부분이
1. 사용하려는 위치 기록이 경로에 해당하는데, DB에 값을 어떻게 저장할지 
2. 이미지같은 경우에는 이미지를 DB에 직접 넣을 수 없으니까 저장소 접근 절대경로를 저장시키는게 맞는거 같고, 추가적으로 하루 일기에 이미지 갯수가 몇개인지 모르면 이걸 이미지경로1, 이미지경로2 이런식으로 해서 갯수에 제한을 둘 건지 아니면 이미지 경로만 갖고있는 테이블을 하나 더 만드는게 좋을지 

두가지 있어서 의견좀 주세요

**Comment by jungmin88** [comment]
1. 경로는 그대로 좌표값을 저장하면 좋을거 같고 좌표값별 시간도 저장하는 항목 있으면 좋을거 같음
2. 이미지 경로에 동의하고 일단 갯수제한은 없는게 간단하지 않을까 생각함
    추후에 이미지 저장시 이름을 시간데이터 기준으로 저장하면서 정렬하면 좋을꺼 같음
    일단은 테이블은 최대한 안만드는게 좋지 않을까 생각함

**Comment by ghost** [comment]
맞져어~

**Comment by ghost** [comment]
되는거 맞나여?
